config/routes.rb
Rails.application.routes.draw do

devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'registrations' }

  resources :movies do
    resources :wishlist_movies, only: [:index, :new, :create, :destroy]
    resources :downloads, only: [:index, :new, :create, :destroy]
  end

  resources :genres, except: :show

  root to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/download.rb
class Download < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :user_id, :movie_id, presence: :true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :categories
  has_many :movies, through: :categories
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :downloads, dependent: :destroy
  has_many :wishlist_movies, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :genres, through: :categories

  validates :name, :duration, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  has_many :downloads
  has_many :wishlist_movies

  # validates :first_name, :last_name, presence: :true
end

app/models/wishlist_movie.rb
class WishlistMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :user_id, :movie_id, presence: :true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(paramas[:id])
    @user.update(event_params)
    redirect_to accounts_update_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to accounts_destroy
  end

end

 private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def index
    @downloads = Download.all
  end

# We are not using this guys
  # def new
  #   @download = Download.new
  #   redirect_to downloads_path, method: :create
  # end

  def create
    @download = Download.new
    @download.movie = Movie.find(params[:movie_id])
    @download.user = User.find(current_user)
    if @download.save
      redirect_to movie_downloads_path(params[:movie_id])
    else
      raise 'Error'
  end
 end

  def destroy
    @download = Download.find(params[:id])
    @download.destroy
    redirect_to movie_downloads_path
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :find_genre, only: [:edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.create(genre_params)
    redirect_to genres_path
  end

  def edit
  end

  def update
    @genre.update(genre_params)
    redirect_to genres_path
  end

  def destroy
    @genre.destroy
    redirect_to genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def find_genre
    @genre = Genre.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :find_movie, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @q = params[:q]
    if @q
      @movies = Movie.where("name ILIKE ? OR director ILIKE ? OR summary ILIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      @movies = Movie.all
    end
  end

  def show
  end

  def new
    @movie = Movie.new
    authorize @movie
  end

  def create
    @movie = Movie.create(movie_params)
    redirect_to movie_path(@movie)
  end

  def edit
    authorize @movie
  end

  def update
    @movie.update(movie_params)
    redirect_to movie_path(@movie)
  end

  def destroy
    authorize @movie
    @movie.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movies).permit(:name, :director, :duration, :genre, :summary)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    if resource.save
      UserMailer.welcome(resource).deliver_now
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/wishlist_movies_controller.rb
class WishlistMoviesController < ApplicationController
  def index
    @wishlist = WishlistMovie.all
  end

  # def new
  #   @wishlist = Wishlist.new
  #    redirect_to new_movie_wishlist_movie_path, method: :create
  # end

  def create
    @wishlist = WishlistMovie.new
    @wishlist.movie = Movie.find(params[:movie_id])
    @wishlist.user = User.find(current_user)
    if @wishlist.save
      redirect_to movie_wishlist_movies_path(params[:movie_id])
    else
      raise 'error'
    end
  end

  def destroy
    @wishlist = WishlistMovie.find(params[:id])
    @wishlist.destroy
    redirect_to movie_wishlist_movies_path
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/wishlist_movies_helper.rb
module WishlistMoviesHelper
end

app/views/accounts/destroy.html.erb
<h1>Accounts#destroy</h1>
<p>Find me in app/views/accounts/destroy.html.erb</p>

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/accounts/update.html.erb
<h1>Accounts#update</h1>
<p>Find me in app/views/accounts/update.html.erb</p>

app/views/downloads/create.html.erb
<h1>Downloads#create</h1>
<p>Find me in app/views/downloads/create.html.erb</p>

app/views/downloads/destroy.html.erb
<h1>Downloads#destroy</h1>
<p>Find me in app/views/downloads/destroy.html.erb</p>

app/views/downloads/index.html.erb
<h1>Welcome to your downloads page</h1>
<p>This is your downloaded movies</p>

<ul>
<% @downloads.each do |download| %>
  <li><%= download.movie.name %> <%= download.movie.summary %> </li>
   <div class="btn-delete">
    <div class="btn btn-danger">
      <%= link_to 'Delete downloaded movie', movie_download_path(download.movie, download), method: :delete %>
    </div>
  </div>


  <% end %>
</ul>

app/views/downloads/new.html.erb
<h1>Downloads#new</h1>
<p>Find me in app/views/downloads/new.html.erb</p>

app/views/genres/edit.html.erb
<h1>Edit Genre</h1>

<%= simple_form_for(@genre) do |f| %>
<%= f.input :name  %>
<%= f.submit "Save" %>
<% end %>

app/views/genres/index.html.erb
<h2>Genres</h2>

<div class="genres-list">
  <ul>
    <% @genres.each do |genre| %>
    <li>
      <%= genre.name %>
      <div class="btn-events">
        <div class="btn btn-danger">
          <%= link_to "Delete Genre", genre_path(genre), method: :delete %>
        </div>
      </div>
      <div class="btn-events">
  <div class="btn btn-danger">
    <%= link_to "Edit Genre", edit_genre_path(genre) %>
  </div>
</div>
    </li>
    <% end %>
  </ul>
</div>

<div class="btn-events">
  <div class="btn btn-danger">
    <%= link_to "All Films", movies_path %>
  </div>
</div>

<div class="btn-events">
  <div class="btn btn-danger">
    <%= link_to "Add Genre", new_genre_path %>
  </div>
</div>

app/views/genres/new.html.erb
<h2>Add a New Genre</h2>

<%= form_for(@genre) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

   <%= f.submit %>
<% end %>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h1>Welcome to filmsy</h1>

      <% if @q %>
      <h2>You've searched for <%= @q %></h2>
      <% else %>
      <h2>Trending movies</h2>
      <% end %>

      <div class="movie-list">

          <% if @movies %>
          <ul>
            <% @movies.each do |movie| %>
            <li>
              <%= link_to "#{movie.name}", movie_path(movie) %>
            </li>
            <% end %>
          </ul>
          <% else %>
          <% raise "error" %>
        <%= "No results" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<h2>Add a New Film</h2>

<%= form_for(@movie) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :director %>
  <%= f.text_field :director %>

  <%= f.label :summary %>
  <%= f.text_field :summary %>

  <%= f.label :duration %>
  <%= f.select :duration, (1..25).to_a %>

  <%= f.label :genres %>
  <%= f.select :genres, @genres_and_ids%>

  <%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<div class="title">
  <h2><%= @movie.name %></h2>
</div>

<div class="movie-info">
  <h4><%= "Director: #{@movie.director}" %></h4>
  <p><%= "Duration: #{@movie.duration}" %></p>
  <p>
    Genre:
    <% @movie.genres.each do |genre| %>
      <%= genre.name %>
    <%end%>
  </p>
  <p><%= "Synopsis: #{@movie.summary}" %></p>
</div>


<div class="option-buttons">

  <% if policy(@movie).edit? %>
    <div class="button-edit">
      <div class="btn btn-danger">
        <%= link_to 'Edit Film', edit_movie_path(@movie) %>
      </div>
    </div>
  <% end %>

  <% if policy(@movie).destroy? %>
    <div class="btn-delete">
      <div class="btn btn-danger">
        <%= link_to 'Delete Film', movie_path(@movie), method: :delete %>
      </div>
    </div>
  <% end %>

  <div class="btn-events">
    <div class="btn btn-danger">
      <%= link_to "All Films", movies_path %>
    </div>
  </div>

</div>

 <div class="btn-add">
    <div class="btn btn-danger">
      <%= link_to 'Download Movie', movie_downloads_path(@movie), method: :create %>
    </div>
  </div>


<div class="btn-add">
    <div class="btn btn-danger">
      <%= link_to 'Add to wishlist', movie_wishlist_movies_path(@movie), method: :create %>
    </div>
  </div>


<div class="social-buttons">
  <ul>
    <li><a href="#" target="blank" class="btn"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
    <li><a href="#" target="blank" class="btn"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
    <li><a href="#" target="blank" class="btn"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
  </ul>
</div>

app/views/movies/update.html.erb
<h1>Movies#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>

app/views/wishlist_movies/create.html.erb
<h1>WishlistMovies#create</h1>
<p>Find me in app/views/wishlist_movies/create.html.erb</p>

app/views/wishlist_movies/destroy.html.erb
<h1>WishlistMovies#destroy</h1>
<p>Find me in app/views/wishlist_movies/destroy.html.erb</p>

app/views/wishlist_movies/index.html.erb
<h1>Welcome to your wishlist page</h1>
<p>This is your wishlist</p>



<ul>
<% @wishlist.each do |wishlist| %>
  <li><%= wishlist.movie.name %> (<%= wishlist.movie.summary %>)
      <div class="btn-delete">
    <div class="btn btn-danger">
      <%= link_to 'Delete movie from your wishlist', movie_wishlist_movie_path(wishlist.movie, wishlist), method: :delete %>
    </div>
  </div>
  </li>

  <% end %>
</ul>

app/views/wishlist_movies/new.html.erb
<h1>WishlistMovies#new</h1>
<p>Find me in app/views/wishlist_movies/new.html.erb</p>